name: Deploy Frontend to S3 & CloudFront

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' 

      - name: Enable Corepack and Prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate # Or pnpm@8 or pnpm@9 if you need a specific version

      - name: Install root dependencies (monorepo)
        run: pnpm install --no-frozen-lockfile

      - name: Build Frontend
        run: pnpm next build

      - name: Configure AWS Credentials with IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./out/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --acl public-read

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"